### ISSUE TITLE
Choosing MD-only as source results in empty entries

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#1046]
With certain searches, such as 'eradicate', some of the results show a header but no other information, in particular a definition, e.g.

<img width="431" alt="image" src="https://user-images.githubusercontent.com/15003407/149639559-3dc6f013-9297-4f7b-bb46-c6c7a53ff47f.png">

When then searching with 'manisikanis', one gets the same empty result - it is analyzed as a diminutive, which is getting me to think whether that might be the source of the issue:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/15003407/149639585-70fb6080-ae17-428f-a0ee-7c4f97ee8620.png">

... as the pre-diminutive form does have an occurrence in MD, cf.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/15003407/149639635-a60d715a-84a6-4380-bcdf-14fd610940cb.png">

**Comment by aarppe** [comment]
Later on, I realized that it appears that what is needed is pressing ENTER at the end of the search string - which is a divergence from earlier behavior  where results are provided as the string is being typed, not requiring a final ENTER.

**Comment by aarppe** [comment]
@nienna73 Hasn't this been fixed?

**Comment by nienna73** [comment]
These are the full results for this wordform (ignore the "True"):

<img width="840" alt="Screen Shot 2022-04-07 at 3 56 00 PM" src="https://user-images.githubusercontent.com/28357720/162326402-f161edaa-ba23-43ce-bda8-dea045b2b06e.png">

What is the expected behaviour here when selecting MD only?
Since there are no definitions for this wordform in MD, should it not appear at all?
There are definitions for the uninflected wordform, though, so should those definitions still appear?

**Comment by nienna73** [comment]
This is how I would expect this to behave:

<img width="850" alt="Screen Shot 2022-04-07 at 4 00 04 PM" src="https://user-images.githubusercontent.com/28357720/162326845-60171c06-5b18-43d3-b882-42a5b1a82d1e.png">

Is this correct?

**Comment by aarppe** [comment]
As a general note, I'd think that if our analyzer can find a lemma that exists in MD (even if that is through derivational analysis as in the case of _manisikanis_ -> _manisikan_), then the lemma should be shown.

Of course, in this particular case there would not be a definition for the actual diminutive in MD.
