### ISSUE TITLE
Filter search results by user-selected dictionary sources

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/morphodict#126]
Prerequisite: #125 

Enables the "advanced search" dropdown that allows one to filter on dictionary source.

Addresses the following user story:

> As a Cree language educator, I want to see search results ONLY from certain dictionary sources

 - [x] Requires new UX [Diane]
 - [x] Requires _accessible_ HTML/CSS [Eddie]
 - [x] Requires database implementation [Matt or Eddie]

**Comment by eddieantonio** [comment]
Note: I deleted my first attempt at the HTML in this commit: ae6c0c9d7567ba77ad26718e2103c5963360a31a.

    git revert ae6c0c9d7567ba77ad26718e2103c5963360a31a

To get the code back.

**Comment by eddieantonio** [comment]
@nienna73 here are the old mockups that our UX deverloper made in 2019:

![Screen Shot 2021-07-21 at 1 39 41 PM](https://user-images.githubusercontent.com/2294397/126550202-f80169e6-0d64-41bd-a457-86eb14971e3e.png)
![Screen Shot 2021-07-21 at 1 38 31 PM](https://user-images.githubusercontent.com/2294397/126550199-f4b90c45-ce57-48e3-be50-7f35fe4441ad.png)
![Screen Shot 2021-07-21 at 1 38 53 PM](https://user-images.githubusercontent.com/2294397/126550201-49a2ac94-8e5d-4a5f-8d02-c14ffd25f4aa.png)

**Comment by nienna73** [comment]
Do we want to keep this UI or add the dictionary source to the settings page?
Adding the options to the new settings page makes more sense to me.

**Comment by eddieantonio** [comment]
> Do we want to keep this UI or add the dictionary source to the settings page?
> Adding the options to the new settings page makes more sense to me.

I agree; I think it makes more sense to add it to the settings page, since I think it's actually a niche feature. That being said, I have a personal attachement to the style of those checkboxes! 😂

**Comment by dwhieb** [comment]
I also like this UI! But also agree that the settings page is the place for them.

**Comment by nienna73** [comment]
@aarppe is the idea that a user can select more than one dictionary source at a time? For example, CW **and** MD? Or should they only be able to select one, that is: CW **or** MD (among the other choices)?

**Comment by aarppe** [comment]
The idea is that users could select any combination of sources, so CW alone or MD alone, or both CW and MD (and then more, once we get AECD in as well).

**Comment by nienna73** [comment]
> The idea is that users could select any combination of sources

Okay, that's what I've been trying to do. I'm finding it difficult to set multiple options, so I wanted to clarify this was actually the goal.

**Comment by nienna73** [comment]
I came across an edge case in development:
<img width="860" alt="Screen Shot 2021-10-04 at 2 42 23 PM" src="https://user-images.githubusercontent.com/28357720/135922251-122a35be-18ca-4a31-af60-8176603cf95e.png">

What do we do when the search result is a form of a word from a different dictionary, like in the example above?
Should I include the definition of mîpit (in this case)?
Or completely remove nîpit from the results?

**Comment by dwhieb** [comment]
@nienna73 Is the above screenshot filtering what currently happens when filtering for MD entries, or for CW entries?

**Comment by nienna73** [comment]
That's a good question. The example above is showing only MD results.

I found a perhaps better example, still filtering to show just MD results:

<img width="854" alt="Screen Shot 2021-10-04 at 3 50 22 PM" src="https://user-images.githubusercontent.com/28357720/135929672-344e83d1-9a05-4489-97cf-5907e95e1331.png">

**Comment by dwhieb** [comment]
@nienna73 Ok so to clarify: This second example is supposed to be showing only MD results, but it includes a CW entry because _ayiwinisa_ is recognized as a form of the CW entry _ayiwin_. Do I have it right?

I'm 100% fine with simply not showing either "form of **ayiwin**" or the entry for _ayiwin_ in this case.

Another solution is to remove the entry for _ayiwin_, but keep "form of **ayiwin**", simply without the link. Also 100% fine with that.

@aarppe Do you have a preference?

**Comment by nienna73** [comment]
@dwhieb Yes, you have that correct. I **think** both of those options are possible, so I'll wait to see what the preferred implementation is.

**Comment by aarppe** [comment]
This is the problem when MD doesn't also include a lemma entry for inflected word-form entries - we'll have more of these cases with some of the imperative verbs. When I was thinking about this almost three years ago, I was considering whether we ought to add "technical" lemma entries, though we might want to run those past speakers - fortunately there's only a few hundred of such forms.

Strictly speaking, if we're not showing content from the other dictionary, then it might be best that we're consistent about that, and neither show the lemma entry, i.e. not show `ayiwin (like: cîmân)` etc., nor the link to the lemma entry (which is in the other dictionary), i.e. `form of ...` etc. However, the FST analysis  can still show that lemma (right now the stem, but I think we'll want to swap back to lemmas eventually), since the FST lexicon is independent of the actual sources.

**Comment by aarppe** [comment]
@nienna73 As part of the dictionary source selection (#126, this issue is getting resolved, but to close that we need to resolve the case of empty results, cf.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/15003407/149639721-215abbd7-e931-4ff4-9e00-fc33fd03ddfb.png">
