### ISSUE TITLE
English search word resulting in Cree words being analyzed

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/morphodict#701]
When searching for the English word _fox_, one of the results, _mahkêsis_, gets analyzed in the process as a diminutive, which it is, but it's not obvious that is actually the desired behavior, cf.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/15003407/111401552-1d014580-868f-11eb-9abf-2fd0bad43aa1.png">

The extra step of analyzing the Cree results that match the English search term is not necessarily what one would expect. In contrast, when searching with the Cree word _mahkêsis_, that is when one would except an analysis of the form as a diminutive, cf.

<img width="462" alt="image" src="https://user-images.githubusercontent.com/15003407/111401875-c3e5e180-868f-11eb-9434-e69d585c75b6.png">

**Comment by eddieantonio** [comment]
There is no re-analysis. Rather, these are matching _two different entries_. Try https://itwewina.altlab.app/search?q=fox+verbose%3A1

The first result has this match data:

```json
{
  "is_lemma": true,
  "wordform_length": 8,
  "target_language_keyword_match": [
    "fox"
  ],
  "source_language_keyword_match": [],
  "morpheme_ranking": 17.7045,
  "cosine_vector_distance": 0.0,
  "relevance_score": 0.08904526406835
}
```

The second result has this:

```json
{
  "is_lemma": false,
  "wordform_length": 8,
  "target_language_keyword_match": [
    "fox"
  ],
  "source_language_keyword_match": [],
  "morpheme_ranking": 17.7045,
  "cosine_vector_distance": 0.0,
  "relevance_score": 0.08904526406835
}
```

It's matching **two different entries**:

```sql
$ sqliite3 db.sqlite3
SELECT id, text, is_lemma, raw_analysis FROM lexicon_wordform;
```

Yields:

| id | text | is_lemma | raw_analysis |
|-:|-|-|-|
| 312392 | mahkêsîs | 0 | `[[], "mahkêsiw", ["+N", "+A", "+Der/Dim", "+N", "+A", "+Sg"]]` |
| 1083977 | mahkêsîs | 1 | `[[], "mahkêsîs", ["+N", "+A", "+Sg"]]` |

Both the readings exist as entries in the database, I believe **because the FST generates both analyses**. Should we be creating entries for +Der/Dim elements that already have entries in the database?
