### ISSUE TITLE
lowercase Nêhiyawêwin

### ISSUE THREAD

**Issue by dwhieb** [UAlbertaALTLab/morphodict#951]
From Arok:

nêhiyawêwin should always be lowercase. We should lowercase the use of this word in the Settings page:

![image](https://user-images.githubusercontent.com/5892997/129309481-a2dc0f1c-e44a-451d-a278-158e53215022.png)

We might actually just consider lowercasing all of them:

* plain English labels
* linguistic labels
* nêhiyawêwin labels

@aarppe Any preference on whether to leave the other choices uppercase or lowercase them?

**Comment by aarppe** [comment]
An option is that we present the options exactly as they are specified, rather than using any "intelligence" to decide what should be formatted, or not.

An additional problem here is that lower-casing _nêhiyawêwin_ is a feature of Standard Roman Orthography, when writing Cree, whereas capitalizing is a convention when writing adjectives for peoples/languages in English. In this respect, capitalizing is entirely _Nêhiyawêwin_ is entirely correct in the English context, so lower-casing would be necessary only when the language of everything in the interface is in Cree.

**Comment by dwhieb** [comment]
I agree morphodict shouldn't be programmatically determining the capitalization for these labels. These labels should be hardcoded somewhere in a language-specific config file or something similar.

You could consider the appearance of _nêhiyawêwin_ here to be a code switch, so that English capitalization rules may not apply.

**Comment by aarppe** [comment]
I'd separate using an endonym vs. exonym from capitalization rules which would be connected with the language of the interface.

In Finnish, names of languages and peoples are not capitalized, whereas names of countries are. So, _Finland_ is _Suomi_, but _Finnish_ (the language) is _suomi_ (or _suomen kieli_) and _Finn(ish)_ (a person) is _suomalainen_. If using endonyms within English text, I'd expect _Suomi_ for both _Finland_ and _Finnish_, for the sake consistency.

One could resort to the code-switching argument, but I suspect is more fancy than most people will appreciate, since we've got some reactions from Cree people why we are not capitalizing the name of their language in English texts.

**Comment by dwhieb** [comment]
I agree with [Haspelmath](https://scholarspace.manoa.hawaii.edu/handle/10125/24725) on this one: endonyms are code-switches, words in foreign languages. _nêhiyawêwin_ isn't an English word and so shouldn't follow English capitalization rules.

I won't press the point though. I'm fine with either. The real deciding factor is probably Arok's opinion anyway.
